<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ks0XaX\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ks0XaX/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container5ks0XaX.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container5ks0XaX\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container5ks0XaX\appAppKernelProdContainer([
    'container.build_hash' => '5ks0XaX',
    'container.build_id' => 'dfb4a659',
    'container.build_time' => 1703711960,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5ks0XaX');
