<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.sms.messagewhiz.callback' shared service.

return $this->services['mautic.sms.messagewhiz.callback'] = new \MauticPlugin\SurgeBundle\Integration\Messagewhiz\MessagewhizCallback(($this->services['mautic.sms.helper.contact'] ?? $this->load('getMautic_Sms_Helper_ContactService.php')), ($this->services['mautic.sms.messagewhiz.configuration'] ?? $this->load('getMautic_Sms_Messagewhiz_ConfigurationService.php')));
