<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVRtjE9x\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVRtjE9x/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerVRtjE9x.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerVRtjE9x\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerVRtjE9x\appAppKernelProdContainer([
    'container.build_hash' => 'VRtjE9x',
    'container.build_id' => 'ce8f4775',
    'container.build_time' => 1703196283,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVRtjE9x');
