<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUYAU2da\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUYAU2da/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerUYAU2da.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerUYAU2da\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerUYAU2da\appAppKernelProdContainer([
    'container.build_hash' => 'UYAU2da',
    'container.build_id' => '1f509189',
    'container.build_time' => 1703711277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUYAU2da');
