<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mautic.sms.messagewhiz.configuration' shared service.

return $this->services['mautic.sms.messagewhiz.configuration'] = new \MauticPlugin\SurgeBundle\Integration\Messagewhiz\Configuration(($this->services['mautic.helper.integration'] ?? $this->getMautic_Helper_IntegrationService()));
